spring.application.name=warehouse-gateway

# vault
spring.cloud.vault.uri=${VAULT_URI}
spring.cloud.vault.token=${VAULT_SECRET_KEY} # store in .env
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.application-name=myapp
spring.cloud.vault.kv.default-context=auth-service
spring.cloud.vault.kv.profile=dev

# JWT
jwt.secret=${JWT_SECRET}
jwt.accessTokenExpiryMs=900000
jwt.refreshTokenExpiryMs=604800000
jwt.internalSecret=${INTERNAL_SECRET}

# health actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# CORS configuration for Spring Cloud Gateway
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true